# Generated by Django 5.0.5 on 2025-05-17 16:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('department', models.CharField(choices=[('empty', 'Не выбрано'), ('accept', 'Здравпункт'), ('KD', 'Коммерческая дирекция (КД)'), ('OS', 'Отдел снабжения (ОС)'), ('ORP', 'Отдел по работе с персоналом (ОРП)'), ('FEO', 'Финансово-экономический отдел (ФЭО)'), ('OHR', 'Охрана труда (ОТ)'), ('PR', 'Пресс-служба (PR)')], default='empty', max_length=50, verbose_name='Отдел')),
                ('file', models.FileField(blank=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'ppt', 'pptx', 'xls', 'xlsx', 'pdf'])], verbose_name='Файл')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_processing', 'В обработке'), ('accept', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=50, verbose_name='Статус')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackauthor', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
                'ordering': ['-pk'],
            },
        ),
    ]
